### ISSUE TITLE
As an Open Data Hub Manager I want to go live with the beta version of the Data Browser 2.0, to start using it and collect feedbacks from real users

### ISSUE THREAD

**Issue by sseppi** [noi-techpark/it.bz.opendatahub.databrowser#251]
The URL of the tool will be: 
v2-beta.databrowser.opendatahub.com

To go live we need:
- [x] domain
- [x] tls certificate
- [x] keycloak config
- [x] replication of the testing pipeline also for the production environment.

Deadline Golive: max 24/01

**Comment by gappc** [comment]
Nice work, the Data Browser is online at https://v2-beta.databrowser.opendatahub.com/

There is just one minor issue: direct opening of pages (except the start page) results in a 404, e.g. try to open https://v2-beta.databrowser.opendatahub.com/dataset-overview, it gives a 404. The same goes for page reloads.

@dulvui Could you please take a look at it? Thank you

**Comment by dulvui** [comment]
@gappc The problem is fixed now.
I added on the S3 bucket on error a redirect to index.html, like it is set on the testing environment https://databrowser.opendatahub.testingmachine.eu/
But I saw that the problem is that direct links give 404, then by redirecting to index.html the vue routing engine loads the correct page as you can see in the console of image below.
![image](https://user-images.githubusercontent.com/12729238/211789282-a4a8060d-c3ba-41c2-a1e7-d018382812e1.png)
Is this the correct behavior of the vue router?

**Comment by gappc** [comment]
@dulvui it works as intended, thank you for the fix :+1:

**Comment by gappc** [comment]
@sseppi can we close this issue?

**Comment by sseppi** [comment]
@dulvui I see that you left the issue on the lain Release on production, did you forgot to shift it or is there something missing?

**Comment by dulvui** [comment]
@sseppi  Yes I forgot. I will close it now
